### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by onbjerg** [tylerreckart/hyperblue#1]
```
bundle.js:1 /Users/onbjerg/.hyperterm_plugins/node_modules/hyperblue/index.js:43
            ${config.css || ''}
             ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at file:///Applications/HyperTerm.app/Contents/Resources/app/dist/bundle.js:1:10827
    at Array.map (native)
```

Broken as of https://github.com/tylerreckart/hyperblue/commit/3bf47d78fc8ba030d473817681c0faa12aa72ab4

**Comment by onbjerg** [comment]
@tylerreckart Any chance you could publish this to npm?

**Comment by tylerreckart** [comment]
Yeah I'll bump it and publish
